### PR TITLE
Update toggleFriendActivity svg

### PR DESCRIPTION
**Pull request by niruvibes**
please do this, i spent hours on it

### CODE REVIEW

**Comment by TheGeeKing** [comment]
Can you rename your commit with a more friendly and relevant name?

**Comment by niruvibes** [comment]
ok u did it
why did u ask me

**Comment by TheGeeKing** [comment]
> Can you rename your commit with a more friendly and relevant name?

Your commit. I renamed the pr but not the commit.

**Comment by niruvibes** [comment]
yes

**Pull request merged**
